/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "on-tertiary-fixed": "#271901",
        "tertiary-fixed": "#fcdeb5",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-high": "#eae7e9",
        "tertiary-fixed-dim": "#dec29a",
        "on-secondary-container": "#586377",
        outline: "#76777d",
        "on-surface": "#1b1b1d",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#98805d",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        background: "#fcf8fa",
        "secondary-fixed-dim": "#bcc7de",
        "inverse-on-surface": "#f3f0f2",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c6c6cd",
        "on-background": "#1b1b1d",
        "secondary-container": "#d5e0f8",
        "on-secondary-fixed": "#111c2d",
        "on-primary-container": "#7c839b",
        tertiary: "#000000",
        "on-error": "#ffffff",
        "surface-container": "#f0edef",
        "on-surface-variant": "#45464d",
        "surface-dim": "#dcd9db",
        surface: "#fcf8fa",
        "error-container": "#ffdad6",
        "primary-container": "#131b2e",
        "surface-tint": "#565e74",
        "surface-container-highest": "#e4e2e4",
        "on-error-container": "#93000a",
        secondary: "#545f73",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        primary: "#000000",
        "tertiary-container": "#271901",
        "primary-fixed": "#dae2fd",
        "inverse-surface": "#303032",
        "on-tertiary-fixed-variant": "#574425",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d8e3fb",
        "surface-container-low": "#f6f3f5",
        "inverse-primary": "#bec6e0",
        "surface-bright": "#fcf8fa",
        "surface-variant": "#e4e2e4",
        "accent-green": "#10b981"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "stack-xl": "48px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        gutter: "24px",
        unit: "4px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-lg": "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        geist: ["Geist", "sans-serif"]
      }
    },
  },
  plugins: [],
};
